# Generated by Django 2.0.5 on 2019-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
